---
name: Check Step Output

on:   # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

jobs:
  build:
    name: check last step
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Unique Command Name
        run: |
          INSTANCE_NAME="$(echo test-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT})"
          echo "INSTANCE_NAME=${INSTANCE_NAME}" | tee -a $GITHUB_ENV
      - name: Check output
        run: |
          echo ${{ toJson(steps) }}
          echo ${{ toJson(steps.build.outputs) }}
