---
name: 4 - Automated CKAN Jobs

on:   # yamllint disable-line rule:truthy
  schedule:
    - cron: '30 7 * * *'       # Tracking Update -- every day at 7:30am UTC
    - cron: '0 3 * * *'        # S3 Sitemap Update -- every day at 3am UTC
    - cron: ${{ env.TEST }}        # Harvester Check -- every 15 mins
    - cron: '0 4 * * *'        # DB-Solr-Sync -- every day at 4am UTC
    - cron: '0 5 * * *'        # Check Stuck Jobs -- every day at 5am UTC

env:
  TEST: '0/5 * * * *'

jobs:
  ckan-auto-command:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        schedule: ['30 7 * * *', '0 3 * * *', $TEST, '0 4 * * *', '0 5 * * *']   # yamllint disable-line rule:line-length
        environ: [development, staging, prod]
        include:
          - app: catalog-admin
          - schedule: '30 7 * * *'
            command: "ckan geodatagov tracking-update"
          - schedule: $TEST
            command: "ckan harvester run"
          - schedule: '0 4 * * *'
            command: "ckan geodatagov db-solr-sync"
          - schedule: '0 5 * * *'
            command: "ckan geodatagov check-stuck-jobs"
          - schedule: '0 3 * * *'
            command: "ckan geodatagov sitemap-to-s3"
          - schedule: '0 3 * * *'
            app: catalog-gather
          - environ: development
            ram: 1G
          - environ: staging
            ram: 3G
          - environ: prod
            ram: 3G
        exclude:
          - schedule: '0 3 * * *'
            environ: development
          - schedule: '0 3 * * *'
            environ: staging
          - schedule: '0 5 * * *'
            environ: development
          - schedule: '0 * * * *'
            environ: [development, staging]
    name: ${{ matrix.command }} - ${{matrix.environ}}
    runs-on: ubuntu-latest
    environment: ${{matrix.environ}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Unique Command Name
        # yamllint disable rule:line-length
        run: |
          INSTANCE_NAME="$(echo ${{ matrix.command }}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT})"
          echo "INSTANCE_NAME=${INSTANCE_NAME}" | tee -a $GITHUB_ENV
          # yamllint enable rule:line-length
      - name: ${{ matrix.command }}
        if: ${{ github.event.schedule == matrix.schedule }}
        run: |
          echo ${{ matrix.command }}
          echo ${{ matrix.app }}
