name: 'echo'
on:
  pull_request:
  workflow_dispatch:

jobs:
  test-redirect-abnormal:
    name: 'Echo issues -- redirect strange'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: echo
      run: |
        sudo chmod 766 /etc/hosts
        echo -e "127.0.0.1\ttest.com" >> tee -a /etc/hosts
        ping -c 4 test.com
  test-pipe:
    name: 'Echo issues -- pipe'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: echo
      run: |
        sudo chmod 766 /etc/hosts
        echo -e "127.0.0.1\ttest.com" | tee -a /etc/hosts
        ping -c 4 test.com
  test-redirect-normal:
    name: 'Echo issues -- redirect normal'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: echo
      run: |
        sudo chmod 766 /etc/hosts
        echo -e "127.0.0.1\ttest.com" >> /etc/hosts
        ping -c 4 test.com
