---
name: Publish & Deploy Template

on:
  workflow_dispatch:

jobs:
  deploy:
    name: github curl api
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Cancel Older Versions
        run: |
          ids=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/issue_creation.yml/runs" | jq '.workflow_runs[] | select(.status=="in_progress") | .id');
          rids=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/issue_creation.yml/runs" | jq '.workflow_runs[] | select(.status=="completed") | .id');
          echo $ids
          echo $rids
          for id in "${ids[@]}"; do
            if [[ "$id" != "${{ github.run_id }}" ]]; then
              curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/gsa/${{ github.repository }}/actions/runs/$id/cancel";
            fi
          done;
