on:
  push:
  workflow_dispatch:
    inputs:
      options:
        description: 'Check for Successful Run'
        type: boolean
        required: true
        default: true

name: Create an issue on push
permissions:
  contents: read
  issues: write 
  pull-requests: read
  repository-projects: read
  actions: read

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ (github.event.inputs.options) || (github.event_name == 'push') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_JOB: ${{ toJson(github)['job'] }}
          GITHUB_ATTEMPTS: ${{ github.run_attempt }}
          LAST_COMMIT: ${{ github.sha }}
          LAST_RUN_BY: ${{ github.actor }}
        with:
          filename: .github/issue.md
          update_existing: true
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/nickumia-reisys/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
