on:
  push:
  workflow_dispatch:
    inputs:
      options:
        description: 'Test Failure?'
        type: boolean
        required: true
        default: true

name: Create an issue on push
permissions:
  contents: read
  issues: write 

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ github.event.inputs.options }}
        update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issue.md
