on:
  push:
  workflow_dispatch:
    inputs:
      options:
        description: 'Check for Successful Run'
        type: boolean
        required: true
        default: true

name: Create an issue on push
permissions:
  contents: read
  issues: write 

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ github.event.inputs.options }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/issue.md
          update_existing: true
