---
name: Build Checks

on:
  push:
  pull_request:
    types: 
      - opened
      - labeled
  workflow_dispatch:

jobs:
  lint:
    if: i${{ github.event_name == 'push' }}
    name: Python Lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.6.1']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run lint
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics

  build:
    if: ${{
      github.event_name == 'pull_request' && github.event.action == 'opened' ||
      github.event_name == 'pull_request' && github.event.action == 'labeled' ||
      github.event_name == 'workflow_dispatch' }}
    name: Build
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: true
          ref: ${{ github.base_ref }}
      - run: |
          git config --global --add safe.directory /__w/github-action-test/github-action-test
          git config --global user.name "Auto Nick"
          git config --global user.email "nickumia6@gmail.com"
          echo "$(date)" > new_date
          git add .
          git commit -m "update: timestamp"
          git push --force
