---
name: Check for Snyk Vulnerabilities

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # every day at 12pm UTC

jobs:
  snyk:
    name: snyk test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install snyk -g
          pip3 install -r requirements.txt
      - name: Run Snyk Scan
          snyk test --file=requirements.txt --json-file-output=scan.json

          # If there are no vulnerabilities, exit!
          [[ "$(jq '.ok' scan.json)" == "true" ]] && exit 0;
