name: 'type'
on:
  pull_request:
  workflow_dispatch:

jobs:
  test-type-directions:
    name: 'type --help'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: man type
      run: |
        type --help || exit 0

  test-type-p:
    name: 'type -p'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: type -p
      run: |
        type -p git apt

  test-type-tf-apply:
    name: 'type -p in dflook tf apply'
    runs-on: ubuntu-latest
    env:
      TERRAFORM_PRE_RUN: |
          export AWS_IAM_AUTH_VERSION_URL="https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator"
          curl -f -LO ${AWS_IAM_AUTH_VERSION_URL} && chmod +x aws-iam-authenticator
          # Check that aws-iam-authenticator was installed
          aws-iam-authenticator --version

          # Try to find it
          type -ap git apt aws-iam-authenticator

    steps:
      - name: terraform apply (development)
        uses: dflook/terraform-apply@v1
        with:
          path: .
          label: nothing
          workspace: nothing
          auto_approve: true
