
name: 'yq'
on:
  workflow_dispatch:

jobs:
  test-yq:
    name: 'Echo issues -- redirect normal'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: echo
      run: |
        export VERSION=v4.2.0 BINARY=yq_linux_amd64
        sudo apt-get update && sudo apt-get install curl
        curl -sL https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz | tar xz && mv ${BINARY} /usr/bin/yq
        yq --help
        yq --version
